### ISSUE TITLE
Key error when single non-routable IP is passed to quick() function

### ISSUE THREAD

**Issue by dhvanilshah-crest** [GreyNoise-Intelligence/pygreynoise#142]
While using GreyNoise SDK, a _KeyError Exception_ is raised when any internal IP address is provided.

For example,
`greynoise quick 10.0.11.34` returns the following traceback:

```Traceback (most recent call last):
  File "C:\Python27\Scripts\greynoise-script.py", line 11, in <module>
    load_entry_point('greynoise==0.3.0', 'console_scripts', 'greynoise')()
  File "c:\python27\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python27\lib\site-packages\greynoise\cli\decorator.py", line 105, in wrapper
    return function(api_client, *args, **kwargs)
  File "c:\python27\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\python27\lib\site-packages\greynoise\cli\decorator.py", line 30, in wrapper
    result = function(*args, **kwargs)
  File "c:\python27\lib\site-packages\greynoise\cli\decorator.py", line 60, in wrapper
    return function(*args, **kwargs)
  File "c:\python27\lib\site-packages\greynoise\cli\decorator.py", line 164, in wrapper
    return function(*args, **kwargs)
  File "c:\python27\lib\site-packages\greynoise\cli\subcommand.py", line 95, in quick
    results.extend(api_client.quick(ip_addresses=ip_addresses))
  File "c:\python27\lib\site-packages\greynoise\api.py", line 218, in quick
    ip_address = api_result["ip"]
KeyError: 'ip'
```
APIs for getting noise status returns different result in case of internal IPs. For instance:
1. In case of `noise/quick/{ip_address}` endpoint, the response for IP = 10.0.11.34 will be:
```
{
    "error": "non-routable ip"
}
```
2. In case of `noise/multi/quick` endpoint, the response for IP = 10.0.11.34 is:
```
{
    "ip": "10.0.11.34",
    "noise": false,
    "code": "0x07"
}
```

In this case, we can solve the _KeyError Exception_ in these two ways:

1. To make the response of both the APIs consistent. But this might have an impact on the existing integrations using the above APIs.
2. Handle the Exception in the code:
Replace this in api.py line 240 and 260
```
api_results.append(self._request(endpoint))
```
with
```
response = self._request(endpoint)
if "non-routable ip" in response.values():
    response["ip"] = ip_address
    response["noise"] = False
    response["code"] = "0x07"
api_results.append(response)
```

**Comment by andrew-morris** [comment]
@jcollado can you handle this bad boy?

**Comment by jcollado** [comment]
@dhvanilshah-crest Thanks for reporting the issue.

This is actually a problem that I had a couple of days ago and that is fixed already in the `implement-filter` branch. I'll mark this bug a fixed when I create the PR for that branch.

**Comment by andrew-morris** [comment]
@jcollado you're the man

**Comment by dhvanilshah-crest** [comment]
@jcollado @andrew-morris 
That's even better!
Could I get to know a rough date when this will be merged?

**Comment by jcollado** [comment]
@dhvanilshah-crest Sure, that should happen by the end of this week.

**Comment by jcollado** [comment]
@dhvanilshah-crest The changes that fix this issue are now merged into master. Please let me know if that's not the case.
