### ISSUE TITLE
Jinja template error on stats query via CLI

### ISSUE THREAD

**Issue by andrew-morris** [GreyNoise-Intelligence/pygreynoise#144]
```
$ greynoise stats "Google LLC"
Traceback (most recent call last):
  File "/usr/local/bin/greynoise", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/greynoise/cli/decorator.py", line 105, in wrapper
    return function(api_client, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/greynoise/cli/decorator.py", line 39, in wrapper
    output = formatter(result, params.get("verbose", False)).strip("\n")
  File "/usr/local/lib/python2.7/site-packages/greynoise/cli/formatter.py", line 45, in wrapper
    output = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/greynoise/cli/formatter.py", line 115, in gnql_stats_formatter
    return template.render(results=results, verbose=verbose, max_width=max_width)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/greynoise/cli/templates/macros.txt.j2", line 34, in template
    {%- set right_width = elements_slice | map(attribute='count') | map('string') | map('length') | max %}
jinja2.exceptions.TemplateAssertionError: no filter named 'max'
```

version:
```$ greynoise version
greynoise 0.3.0
  Python 2.7.16
  Darwin-18.7.0-x86_64-i386-64bit```

**Comment by andrew-morris** [comment]
disregard- I upgraded to the latest code and this seems to have been fixed. Thanks!
