### ISSUE TITLE
greynoise setup not working

### ISSUE THREAD

**Issue by andrew-morris** [GreyNoise-Intelligence/pygreynoise#60]
```
andrew@rpi:~/.local/bin $ ./greynoise setup -k

Error: API key not found.

To fix this problem, please use any of the following methods (in order of precedence):
- Pass it using the -k/--api-key option.
- Set it in the GREYNOISE_API_KEY environment variable.
- Run 'greynoise setup' to save it to the configuration file.

andrew@rpi:~/.local/bin $ ./greynoise setup -k XXXXXXXX

Error: API key not found.

To fix this problem, please use any of the following methods (in order of precedence):
- Pass it using the -k/--api-key option.
- Set it in the GREYNOISE_API_KEY environment variable.
- Run 'greynoise setup' to save it to the configuration file.

andrew@rpi:~/.local/bin $ ./greynoise setup --api-key XXXXXXX

Error: API key not found.

To fix this problem, please use any of the following methods (in order of precedence):
- Pass it using the -k/--api-key option.
- Set it in the GREYNOISE_API_KEY environment variable.
- Run 'greynoise setup' to save it to the configuration file.

andrew@rpi:~/.local/bin $ ./greynoise setup

Error: API key not found.

To fix this problem, please use any of the following methods (in order of precedence):
- Pass it using the -k/--api-key option.
- Set it in the GREYNOISE_API_KEY environment variable.
- Run 'greynoise setup' to save it to the configuration file.

andrew@rpi:~/.local/bin $ ./greynoise setup

Error: API key not found.

To fix this problem, please use any of the following methods (in order of precedence):
- Pass it using the -k/--api-key option.
- Set it in the GREYNOISE_API_KEY environment variable.
- Run 'greynoise setup' to save it to the configuration file.
```

**Comment by jcollado** [comment]
@andrew-morris This is not the behavior I'm getting. I suspect that what you have in `~/.local/bin` might be an old version of the library.

To make sure about that, please run these commands in the `pygreynoise` directory:
```
$ git rev-parse HEAD
a942240da3c93faacf89f3f2628663c2b7d7a947
$ python3 -mvenv venv
$ source venv/bin/activate
$ pip install -r requirements/dev.txt -e .
$ hash -r
$ which greynoise
/home/user/pygreynoise/venv/bin/greynoise
$ greynoise setup -k
Error: -k option requires an argument
 $ greynoise setup -k XXXX
Configuration saved to '/home/user/.config/greynoise/config'
$ greynoise setup --api-key XXXX
Configuration saved to '/home/javi/.config/greynoise/config'
$ greynoise setup
Usage: greynoise setup [OPTIONS]
Try "greynoise setup --help" for help.

Error: Missing option "-k" / "--api-key".
```

**Comment by andrew-morris** [comment]
another user having a similar error on Slack

```
n0x08 6:19 PM
nate@0dayAllday:~/pygreynoise$ greynoise setup --api-key [REDACTED]
Error: API key not found.
(edited)
@Andrew Morris the new client doesn't like me
Matt Lehman 6:20 PM
@n0x08 try with -k I believe
possible it's a bug
n0x08 6:20 PM
same error
```

**Comment by andrew-morris** [comment]
more recreation steps

```$ greynoise setup

Error: API key not found.

To fix this problem, please use any of the following methods (in order of precedence):
- Pass it using the -k/--api-key option.
- Set it in the GREYNOISE_API_KEY environment variable.
- Run 'greynoise setup' to save it to the configuration file.

$ greynoise setup -k heres_a_key

Error: API key not found.

To fix this problem, please use any of the following methods (in order of precedence):
- Pass it using the -k/--api-key option.
- Set it in the GREYNOISE_API_KEY environment variable.
- Run 'greynoise setup' to save it to the configuration file.

$ greynoise setup --api-key heres_a_key

Error: API key not found.

To fix this problem, please use any of the following methods (in order of precedence):
- Pass it using the -k/--api-key option.
- Set it in the GREYNOISE_API_KEY environment variable.
- Run 'greynoise setup' to save it to the configuration file.

$ greynoise -k heres_a_key setup
Traceback (most recent call last):
  File "/home/andrew/.local/bin/greynoise", line 9, in <module>
    load_entry_point('greynoise==0.2.0', 'console_scripts', 'greynoise')()
  File "/home/andrew/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/andrew/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/andrew/.local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/andrew/.local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andrew/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/andrew/.local/lib/python3.5/site-packages/greynoise-0.2.0-py3.5.egg/greynoise/cli/subcommand.py", line 44, in setup
    save_config(config)
  File "/home/andrew/.local/lib/python3.5/site-packages/greynoise-0.2.0-py3.5.egg/greynoise/util.py", line 51, in save_config
    config_parser.set("greynoise", "api_key", config["api_key"])
  File "/usr/lib/python3.5/configparser.py", line 1189, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/lib/python3.5/configparser.py", line 1174, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
andrew@nuc:~/GreyNoise/Projects/pygreynoise$ greynoise --api-key heres_a_key setup
Traceback (most recent call last):
  File "/home/andrew/.local/bin/greynoise", line 9, in <module>
    load_entry_point('greynoise==0.2.0', 'console_scripts', 'greynoise')()
  File "/home/andrew/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/andrew/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/andrew/.local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/andrew/.local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andrew/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/andrew/.local/lib/python3.5/site-packages/greynoise-0.2.0-py3.5.egg/greynoise/cli/subcommand.py", line 44, in setup
    save_config(config)
  File "/home/andrew/.local/lib/python3.5/site-packages/greynoise-0.2.0-py3.5.egg/greynoise/util.py", line 51, in save_config
    config_parser.set("greynoise", "api_key", config["api_key"])
  File "/usr/lib/python3.5/configparser.py", line 1189, in set
    self._validate_value_types(option=option, value=value)
  File "/usr/lib/python3.5/configparser.py", line 1174, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings```

**Comment by andrew-morris** [comment]
Figured out a strange workaround @jcollado 

```
$ greynoise -k key1 setup -k key2
Configuration saved to '/home/andrew/.config/greynoise/config'

$ cat ~/.config/greynoise/config
[greynoise]
api_key = key2
```
